//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JameProjectEntities2 : DbContext
    {
        public JameProjectEntities2()
            : base("name=JameProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<contestDB> contestDB { get; set; }
        public virtual DbSet<Winner> Winner { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
        public virtual DbSet<Image_User> Image_User { get; set; }
    }
}
