//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class contestDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contestDB()
        {
            this.Winner = new HashSet<Winner>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Ingradient { get; set; }
        public string CookingProcess { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string userid { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Winner> Winner { get; set; }
    }
}
