//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datePosted { get; set; }
        public string Rating { get; set; }
        public string Contents { get; set; }
        public string User_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
