//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Ingredients { get; set; }
        public string CookingProcess { get; set; }
        public Nullable<bool> Isfree { get; set; }
        public string Images { get; set; }
    }
}
