//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public string SubscriptionType { get; set; }
        public string user_id { get; set; }
        public string Subscription_Status { get; set; }
        public Nullable<System.DateTime> Subscription_Date { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
