//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptech_Final_E_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winner
    {
        public int Id { get; set; }
        public Nullable<int> Contestid { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual contestDB contestDB { get; set; }
    }
}
